// CAMPSITES
export const ADD_CAMPSITES = 'ADD_CAMPSITES';
export const CAMPSITES_LOADING = 'CAMPSITES_LOADING';
export const CAMPSITES_FAILED = 'CAMPSITES_FAILED';

// Comments
export const ADD_COMMENT = 'ADD_COMMENT';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';

// Promotions
export const ADD_PROMOTIONS = 'ADD_PROMOTIONS';
export const PROMOTIONS_LOADING = 'PROMOTIONS_LOADING';
export const PROMOTIONS_FAILED = 'PROMOTIONS_FAILED';

// Partners
export const ADD_PARTNERS = 'ADD_PARTNERS';
export const ADD_PARTNERS_LOADING = 'ADD_PARTNERS_LOADING';
export const ADD_PARTNERS_FAILED = 'ADD_PARTNERS_FAILED';
